#ifndef _CONFIG_HPP_
#define _CONFIG_HPP_

// BUFFER SETTIGNS
#define BUFFER_ROWS 30
#define BUFFER_COLS 80

// CURSOR SETTINGS
#define START_CURSOR_POS 0

// FILE_SYSTEM
#define FILE_PATH "workingFiles"

// SIDE BAR PANEL FOR CURSOR POS
#define SIDE_CURSOR_PANEL_ROW 30
#define SIDE_CURSOR_PANEL_COL 85


#endif
